# Generated by Django 5.1.4 on 2024-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmanagement',
            name='sub_variant',
        ),
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='SubVariants',
        ),
    ]
